name: Hello Actions
on: push
jobs:
  build:
    name: Hello world action
    runs-on: self-hosted
    steps:
      - run: >
        echo "User ${{ github.event.inputs.username }} ran a workflow manually."
        echo "Because ${{ github.event.inputs.reason }}."
